import { PHOTOS } from "../images";
import type { Comment, CommunityBuild, User } from "../types";

/**
 * Seed community data for the prototype. Replace with `UserRepository` /
 * `BuildRepository` implementations backed by a database.
 */
export const USERS: User[] = [
  {
    id: "u-thomas",
    username: "thomas",
    name: "Thomas",
    avatar: "#2d8a4e",
    location: "Belgium",
    ridingStyle: "Trail Rider",
    bio: "Ardennes singletrack most weekends. I build bikes that climb well enough and descend better than they should.",
    followers: 413,
    following: 88,
    likes: 9120,
    joined: "2024-03-02",
  },
  {
    id: "u-lena",
    username: "lena",
    name: "Lena",
    avatar: "#b4532a",
    location: "Germany",
    ridingStyle: "XC Racer",
    bio: "Marathon and XCO racing in the Black Forest. Every gram counts, every euro too.",
    followers: 1280,
    following: 142,
    likes: 15400,
    joined: "2023-11-18",
  },
  {
    id: "u-marco",
    username: "marco",
    name: "Marco",
    avatar: "#2f4b7c",
    location: "Italy",
    ridingStyle: "Road Climber",
    bio: "Dolomites, espresso, repeat. Lightweight road builds for long days in the mountains.",
    followers: 2210,
    following: 310,
    likes: 22800,
    joined: "2023-06-09",
  },
  {
    id: "u-sofie",
    username: "sofie",
    name: "Sofie",
    avatar: "#7a3e8a",
    location: "Netherlands",
    ridingStyle: "Road Racer",
    bio: "Crits and flat, windy races. Aero first.",
    followers: 905,
    following: 97,
    likes: 7300,
    joined: "2024-05-21",
  },
  {
    id: "u-jonas",
    username: "jonas",
    name: "Jonas",
    avatar: "#8a6d1f",
    location: "Austria",
    ridingStyle: "Enduro",
    bio: "Bike park laps in summer, long enduro days in autumn. Durability over grams.",
    followers: 640,
    following: 120,
    likes: 5100,
    joined: "2024-01-14",
  },
];

const base = { visibility: "public" as const, createdAt: "2026-08-01T10:00:00Z", updatedAt: "2026-09-10T10:00:00Z" };

export const COMMUNITY_BUILDS: CommunityBuild[] = [
  {
    ...base,
    id: "mountain-beast",
    name: "Mountain Beast",
    discipline: "mtb",
    authorId: "u-thomas",
    description: "Long-travel enduro build for the steepest Ardennes lines and summer trips to the Alps.",
    coverImage: PHOTOS.heroMtbJump,
    likes: 4832,
    comments: 214,
    saves: 1290,
    tags: ["Enduro", "29\"", "SRAM Transmission"],
    createdAt: "2026-07-12T09:00:00Z",
    parts: {
      frame: "santa-cruz-megatower",
      fork: "rockshox-zeb-ultimate",
      wheels: "dt-ex-1700",
      tires: "maxxis-dhf-dhr-25",
      groupset: "sram-x0-transmission",
      crankset: "sram-x0-crank",
      cassette: "sram-xs1295",
      chain: "sram-t-type-chain",
      brakes: "sram-code-rsc",
      handlebar: "renthal-fatbar-carbon-35",
      stem: "renthal-apex-35",
      seatpost: "rockshox-reverb-axs",
      saddle: "ergon-sm-enduro-pro",
      pedals: "crankbrothers-stamp-7",
    },
  },
  {
    ...base,
    id: "featherweight-xc",
    name: "Featherweight XC",
    discipline: "mtb",
    authorId: "u-lena",
    description: "My XCO race bike. Wireless drivetrain, carbon everything, no compromises on weight.",
    coverImage: PHOTOS.xcRacerWater,
    likes: 3120,
    comments: 132,
    saves: 870,
    tags: ["XC", "Race", "Lightweight"],
    createdAt: "2026-06-03T09:00:00Z",
    parts: {
      frame: "trek-supercaliber-slr",
      fork: "rockshox-sid-sl-ultimate",
      wheels: "dt-xrc-1200",
      tires: "schwalbe-racing-ray-ralph",
      groupset: "sram-xx-sl-transmission",
      crankset: "sram-xx-sl-crank",
      cassette: "sram-xs1299",
      chain: "sram-t-type-chain",
      brakes: "sram-level-ultimate",
      handlebar: "easton-ec90-sl-318",
      stem: "thomson-elite-x4-318",
      seatpost: "ritchey-wcs-carbon-316",
      saddle: "selle-italia-slr-boost",
      pedals: "shimano-xtr-pd-m9100",
    },
  },
  {
    ...base,
    id: "alpine-climber",
    name: "Alpine Climber",
    discipline: "road",
    authorId: "u-marco",
    description: "Built for the Stelvio and Giau. Light, comfortable and quick to respond.",
    coverImage: PHOTOS.mountainRoad,
    likes: 5210,
    comments: 301,
    saves: 1610,
    tags: ["Road", "Climbing", "Dura-Ace"],
    createdAt: "2026-05-20T09:00:00Z",
    parts: {
      frame: "specialized-aethos",
      fork: "aethos-fork",
      wheels: "shimano-da-c50",
      tires: "conti-gp5000-str-28",
      groupset: "shimano-da-r9200",
      crankset: "shimano-da-crank",
      cassette: "shimano-da-cassette",
      chain: "shimano-da-chain",
      brakes: "shimano-da-br-r9270",
      handlebar: "roval-alpinist-bar",
      stem: "zipp-sc-sl-stem",
      seatpost: "roval-alpinist-seatpost",
      saddle: "sworks-power-mirror",
      pedals: "shimano-da-pd-r9200",
    },
  },
  {
    ...base,
    id: "aero-weapon",
    name: "Aero Weapon",
    discipline: "road",
    authorId: "u-sofie",
    description: "Crit and flat-race bike. Deep wheels, SRAM Red, aero bar.",
    coverImage: PHOTOS.peloton,
    likes: 2890,
    comments: 97,
    saves: 640,
    tags: ["Road", "Aero", "SRAM Red"],
    createdAt: "2026-08-02T09:00:00Z",
    parts: {
      frame: "specialized-tarmac-sl8",
      fork: "tarmac-sl8-fork",
      wheels: "roval-rapide-clx-ii",
      tires: "conti-gp5000-str-28",
      groupset: "sram-red-axs-e1",
      crankset: "sram-red-e1-crank",
      cassette: "sram-red-xg1290",
      chain: "sram-red-flattop",
      brakes: "sram-red-e1-brakes",
      handlebar: "enve-ses-aero-bar",
      stem: "enve-road-stem",
      seatpost: "tarmac-sl8-seatpost",
      saddle: "selle-italia-slr-boost",
      pedals: "look-keo-blade-carbon",
    },
  },
  {
    ...base,
    id: "trail-daily",
    name: "Trail Daily",
    discipline: "mtb",
    authorId: "u-jonas",
    description: "Sensible trail bike: Shimano XT throughout, aluminium wheels, easy to maintain.",
    coverImage: PHOTOS.hardtailHill,
    likes: 1740,
    comments: 66,
    saves: 520,
    tags: ["Trail", "Value", "Shimano XT"],
    createdAt: "2026-08-22T09:00:00Z",
    parts: {
      frame: "canyon-spectral-cf",
      fork: "rockshox-pike-ultimate",
      wheels: "dt-xm-1700",
      tires: "maxxis-dissector-24",
      groupset: "shimano-xt-m8100",
      crankset: "shimano-xt-crank",
      cassette: "shimano-xt-cassette",
      chain: "shimano-xt-chain",
      brakes: "shimano-xt-m8120",
      handlebar: "oneup-carbon-35",
      stem: "raceface-turbine-r-35",
      seatpost: "oneup-v3-dropper",
      saddle: "wtb-volt",
      pedals: "oneup-composite-flat",
    },
  },
  {
    ...base,
    id: "ardennes-stumpy",
    name: "Ardennes Stumpy",
    discipline: "mtb",
    authorId: "u-thomas",
    description: "My everyday trail bike. XTR drivetrain, Magura stoppers, carbon wheels.",
    coverImage: PHOTOS.bikepackingSunset,
    likes: 2210,
    comments: 88,
    saves: 610,
    tags: ["Trail", "Shimano XTR"],
    createdAt: "2026-04-11T09:00:00Z",
    parts: {
      frame: "specialized-stumpjumper-15",
      fork: "fox-36-factory",
      wheels: "reserve-30-sl",
      tires: "maxxis-dhf-dhr-25",
      groupset: "shimano-xtr-m9100",
      crankset: "shimano-xtr-crank",
      cassette: "shimano-xtr-cassette",
      chain: "shimano-xtr-chain",
      brakes: "magura-mt7-pro",
      handlebar: "oneup-carbon-35",
      stem: "raceface-turbine-r-35",
      seatpost: "oneup-v3-dropper",
      saddle: "specialized-power-pro",
      pedals: "shimano-xtr-pd-m9100",
    },
  },
  {
    ...base,
    id: "budget-hardtail",
    name: "Marathon Hardtail",
    discipline: "mtb",
    authorId: "u-lena",
    description: "Light carbon hardtail for marathons, built with durable mid-range parts.",
    coverImage: PHOTOS.groupRideForest,
    likes: 980,
    comments: 41,
    saves: 300,
    tags: ["XC", "Hardtail", "Value"],
    createdAt: "2026-09-01T09:00:00Z",
    parts: {
      frame: "canyon-exceed-cf",
      fork: "rockshox-sid-sl-ultimate",
      wheels: "dt-xm-1700",
      tires: "maxxis-rekon-race-24",
      groupset: "sram-gx-eagle",
      crankset: "sram-gx-crank",
      cassette: "sram-xg1275",
      chain: "sram-gx-chain",
      brakes: "sram-level-ultimate",
      handlebar: "easton-ec90-sl-318",
      stem: "thomson-elite-x4-318",
      seatpost: "ritchey-wcs-carbon-316",
      saddle: "selle-italia-slr-boost",
      pedals: "time-atac-xc8",
    },
  },
  {
    ...base,
    id: "tyrol-enduro",
    name: "Tyrol Enduro",
    discipline: "mtb",
    authorId: "u-jonas",
    description: "Öhlins suspension and Hope brakes — built to survive a season of park laps.",
    coverImage: PHOTOS.riderSmoke,
    likes: 1320,
    comments: 58,
    saves: 410,
    tags: ["Enduro", "Durable"],
    createdAt: "2026-07-30T09:00:00Z",
    parts: {
      frame: "santa-cruz-megatower",
      fork: "ohlins-rxf36",
      wheels: "dt-ex-1700",
      tires: "conti-kryptotal-enduro",
      groupset: "shimano-xt-m8100",
      crankset: "shimano-xt-crank",
      cassette: "shimano-xt-cassette",
      chain: "shimano-xt-chain",
      brakes: "hope-tech4-v4",
      handlebar: "renthal-fatbar-carbon-35",
      stem: "renthal-apex-35",
      seatpost: "fox-transfer-factory",
      saddle: "ergon-sm-enduro-pro",
      pedals: "crankbrothers-stamp-7",
    },
  },
];

export const COMMENTS: Comment[] = [
  { id: "c1", buildId: "mountain-beast", authorId: "u-jonas", body: "ZEB + Code is such a solid combo for park days. How are you finding the Reverb AXS on long descents?", createdAt: "2026-09-20T18:12:00Z" },
  { id: "c2", buildId: "mountain-beast", authorId: "u-lena", body: "Beautiful build. Not for me on a climb, but I'd happily take the shuttle 😄", createdAt: "2026-09-21T08:40:00Z" },
  { id: "c3", buildId: "mountain-beast", authorId: "u-marco", body: "Those 200 mm rotors must be reassuring in the Alps.", createdAt: "2026-09-22T12:05:00Z" },
  { id: "c4", buildId: "featherweight-xc", authorId: "u-thomas", body: "What's the real-world weight with pedals and bottle cages?", createdAt: "2026-09-18T19:22:00Z" },
  { id: "c5", buildId: "alpine-climber", authorId: "u-sofie", body: "Aethos + C50s is a great balance. Did you consider the C36 for climbing days?", createdAt: "2026-09-12T07:10:00Z" },
  { id: "c6", buildId: "aero-weapon", authorId: "u-marco", body: "Fast! How is the Rapide in crosswinds?", createdAt: "2026-09-02T16:45:00Z" },
];

export const getUser = (id: string) => USERS.find((u) => u.id === id);
export const getUserByUsername = (username: string) => USERS.find((u) => u.username === username);
export const getCommunityBuild = (id: string) => COMMUNITY_BUILDS.find((b) => b.id === id);
export const buildsByAuthor = (authorId: string) => COMMUNITY_BUILDS.filter((b) => b.authorId === authorId);
export const commentsFor = (buildId: string) => COMMENTS.filter((c) => c.buildId === buildId);

/** Published build counts include builds not in the seed data. */
export const BUILD_COUNTS: Record<string, number> = { "u-thomas": 24, "u-lena": 11, "u-marco": 17, "u-sofie": 6, "u-jonas": 9 };
