import type { BikeComponent } from "../types";

/**
 * Mountain bike sample catalog.
 *
 * Product names are real. Prices are indicative EUR retail and weights are
 * approximate manufacturer claims — they are sample data for the prototype and
 * must be replaced by a verified component database before launch.
 */
export const MTB_COMPONENTS: BikeComponent[] = [
  // ─── Frames ──────────────────────────────────────────────────────────────
  {
    id: "trek-supercaliber-slr",
    category: "frame",
    disciplines: ["mtb"],
    brand: "Trek",
    model: "Supercaliber SLR Frameset",
    priceEur: 2499,
    weightG: 2100,
    tier: 5,
    ratings: { performance: 9.5, comfort: 6, durability: 7.5, climbing: 10, descending: 6.5 },
    maintenance: "medium",
    compat: {
      wheelSize: "29",
      forkTravelRange: [100, 120],
      travelMm: 80,
      maxTireMm: 61,
      udh: true,
      brakeMount: "flat-mount",
      seatpostFit: "31.6",
    },
    specs: [
      { label: "Material", value: "OCLV Mountain Carbon" },
      { label: "Rear travel", value: "80 mm IsoStrut" },
      { label: "Fork travel", value: "100–120 mm" },
      { label: "Wheel size", value: '29"' },
      { label: "Rear brake mount", value: "Flat mount" },
      { label: "Derailleur hanger", value: "UDH" },
    ],
    summary: "A cross-country race frame built around efficiency and low weight.",
    pros: ["Very light and efficient under power", "Short-travel rear keeps traction on rough climbs", "UDH: ready for SRAM Transmission"],
    cons: ["Limited to 2.4\" tires", "Not designed for aggressive descending"],
    visual: { color: "#1c1f22", accent: "#8a9199", shape: "xc" },
  },
  {
    id: "specialized-stumpjumper-15",
    category: "frame",
    disciplines: ["mtb"],
    brand: "Specialized",
    model: "Stumpjumper 15 Frameset",
    priceEur: 3500,
    weightG: 2650,
    tier: 5,
    ratings: { performance: 9, comfort: 8.5, durability: 8, climbing: 8, descending: 9 },
    maintenance: "medium",
    compat: {
      wheelSize: "29",
      forkTravelRange: [150, 160],
      travelMm: 145,
      maxTireMm: 66,
      udh: true,
      brakeMount: "post-mount",
      seatpostFit: "34.9",
    },
    specs: [
      { label: "Material", value: "FACT 11m carbon" },
      { label: "Rear travel", value: "145 mm" },
      { label: "Fork travel", value: "150–160 mm" },
      { label: "Wheel size", value: '29" (mixed-wheel compatible)' },
      { label: "Rear brake mount", value: "Post mount" },
      { label: "Derailleur hanger", value: "UDH" },
    ],
    summary: "A modern trail frame that balances climbing efficiency with confident descending.",
    pros: ["Excellent all-round trail geometry", "Clears 2.6\" tires", "UDH-compatible"],
    cons: ["Heavier than XC frames", "Premium price"],
    visual: { color: "#2f3a2e", accent: "#b9c2a4", shape: "trail" },
  },
  {
    id: "canyon-spectral-cf",
    category: "frame",
    disciplines: ["mtb"],
    brand: "Canyon",
    model: "Spectral CF Frameset",
    priceEur: 2299,
    weightG: 2750,
    tier: 4,
    ratings: { performance: 8.5, comfort: 8, durability: 8, climbing: 7.5, descending: 9 },
    maintenance: "medium",
    compat: {
      wheelSize: "29",
      forkTravelRange: [150, 160],
      travelMm: 150,
      maxTireMm: 66,
      udh: true,
      brakeMount: "post-mount",
      seatpostFit: "31.6",
    },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Rear travel", value: "150 mm" },
      { label: "Fork travel", value: "150–160 mm" },
      { label: "Wheel size", value: '29"' },
      { label: "Rear brake mount", value: "Post mount" },
      { label: "Derailleur hanger", value: "UDH" },
    ],
    summary: "A playful, capable trail/all-mountain frame with strong value for money.",
    pros: ["Great value carbon frame", "Poppy, playful ride", "UDH-compatible"],
    cons: ["Direct-to-consumer only", "Slightly heavier than the Stumpjumper"],
    visual: { color: "#243a52", accent: "#9fb6cc", shape: "trail" },
  },
  {
    id: "santa-cruz-megatower",
    category: "frame",
    disciplines: ["mtb"],
    brand: "Santa Cruz",
    model: "Megatower CC Frameset",
    priceEur: 3999,
    weightG: 3300,
    tier: 5,
    ratings: { performance: 8.5, comfort: 9, durability: 8.5, climbing: 6.5, descending: 10 },
    maintenance: "medium",
    compat: {
      wheelSize: "29",
      forkTravelRange: [160, 170],
      travelMm: 165,
      maxTireMm: 66,
      udh: true,
      brakeMount: "post-mount",
      seatpostFit: "31.6",
    },
    specs: [
      { label: "Material", value: "Carbon CC" },
      { label: "Rear travel", value: "165 mm VPP" },
      { label: "Fork travel", value: "160–170 mm" },
      { label: "Wheel size", value: '29"' },
      { label: "Rear brake mount", value: "Post mount" },
      { label: "Derailleur hanger", value: "UDH" },
    ],
    summary: "A long-travel enduro frame designed for steep, fast and rough terrain.",
    pros: ["Outstanding stability at speed", "Lifetime frame warranty", "Takes big tires and rotors"],
    cons: ["Heaviest frame in the catalog", "Slower on long climbs"],
    visual: { color: "#5a1f1b", accent: "#e0b7a9", shape: "enduro" },
  },
  {
    id: "canyon-exceed-cf",
    category: "frame",
    disciplines: ["mtb"],
    brand: "Canyon",
    model: "Exceed CF Hardtail Frameset",
    priceEur: 1299,
    weightG: 1050,
    tier: 4,
    ratings: { performance: 8.5, comfort: 5, durability: 8.5, climbing: 10, descending: 5 },
    maintenance: "low",
    compat: {
      wheelSize: "29",
      forkTravelRange: [100, 110],
      travelMm: 0,
      maxTireMm: 61,
      udh: true,
      brakeMount: "flat-mount",
      seatpostFit: "31.6",
    },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Rear travel", value: "Hardtail" },
      { label: "Fork travel", value: "100–110 mm" },
      { label: "Wheel size", value: '29"' },
      { label: "Rear brake mount", value: "Flat mount" },
      { label: "Derailleur hanger", value: "UDH" },
    ],
    summary: "A light carbon hardtail for racing and fast marathon riding.",
    pros: ["Extremely light", "Very little maintenance", "Direct power transfer"],
    cons: ["Harsh on rough descents", "Tire clearance limited to 2.4\""],
    visual: { color: "#e6e6e1", accent: "#2d8a4e", shape: "hardtail" },
  },

  // ─── Forks ───────────────────────────────────────────────────────────────
  {
    id: "fox-36-factory",
    category: "fork",
    disciplines: ["mtb"],
    brand: "Fox",
    model: "36 Factory GRIP X2",
    priceEur: 1199,
    weightG: 1698,
    tier: 5,
    ratings: { performance: 9.5, comfort: 9, durability: 8, climbing: 7, descending: 9.5 },
    maintenance: "high",
    compat: { wheelSize: "29", travelMm: 160, maxTireMm: 66, brakeMount: "post-mount", minRotorMm: 180 },
    specs: [
      { label: "Travel", value: "160 mm" },
      { label: "Stanchions", value: "36 mm Kashima" },
      { label: "Damper", value: "GRIP X2" },
      { label: "Axle", value: "15×110 Boost" },
      { label: "Steerer", value: "Tapered, aluminium" },
      { label: "Brake mount", value: "Post mount, 180 mm native" },
    ],
    summary: "Fox's benchmark trail/enduro fork with a highly adjustable damper.",
    pros: ["Very supportive, tunable damping", "Stiff chassis for precise steering", "Kashima coating reduces friction"],
    cons: ["Service intervals are frequent for hard riders", "Many adjusters to set up"],
    visual: { stanchion: "kashima" },
  },
  {
    id: "rockshox-pike-ultimate",
    category: "fork",
    disciplines: ["mtb"],
    brand: "RockShox",
    model: "Pike Ultimate",
    priceEur: 919,
    weightG: 1790,
    tier: 4,
    ratings: { performance: 9, comfort: 8.5, durability: 8.5, climbing: 7.5, descending: 8.5 },
    maintenance: "medium",
    compat: { wheelSize: "29", travelMm: 150, maxTireMm: 66, brakeMount: "post-mount", minRotorMm: 180 },
    specs: [
      { label: "Travel", value: "150 mm" },
      { label: "Stanchions", value: "35 mm" },
      { label: "Damper", value: "Charger 3" },
      { label: "Axle", value: "15×110 Boost" },
      { label: "Steerer", value: "Tapered, aluminium" },
      { label: "Brake mount", value: "Post mount, 180 mm native" },
    ],
    summary: "A proven trail fork with a simple, effective damper.",
    pros: ["Easy to set up", "Excellent small-bump sensitivity", "Good value"],
    cons: ["Less adjustable than GRIP X2", "Slightly less stiff than 36/38 mm chassis"],
    visual: { stanchion: "black" },
  },
  {
    id: "fox-34-factory",
    category: "fork",
    disciplines: ["mtb"],
    brand: "Fox",
    model: "34 Factory GRIP X",
    priceEur: 1079,
    weightG: 1610,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7.5, durability: 8, climbing: 8.5, descending: 7.5 },
    maintenance: "high",
    compat: { wheelSize: "29", travelMm: 140, maxTireMm: 64, brakeMount: "post-mount", minRotorMm: 160 },
    specs: [
      { label: "Travel", value: "140 mm" },
      { label: "Stanchions", value: "34 mm Kashima" },
      { label: "Damper", value: "GRIP X" },
      { label: "Axle", value: "15×110 Boost" },
      { label: "Steerer", value: "Tapered, aluminium" },
      { label: "Brake mount", value: "Post mount, 160 mm native" },
    ],
    summary: "A lighter trail fork for efficient all-day riding.",
    pros: ["Lighter than 36 mm forks", "Efficient pedalling platform"],
    cons: ["Less stiff under heavy braking", "Too short for enduro frames"],
    visual: { stanchion: "kashima" },
  },
  {
    id: "ohlins-rxf36",
    category: "fork",
    disciplines: ["mtb"],
    brand: "Öhlins",
    model: "RXF36 m.2",
    priceEur: 1250,
    weightG: 2040,
    tier: 5,
    ratings: { performance: 9.5, comfort: 9.5, durability: 8.5, climbing: 6.5, descending: 9.5 },
    maintenance: "high",
    compat: { wheelSize: "29", travelMm: 160, maxTireMm: 66, brakeMount: "post-mount", minRotorMm: 180 },
    specs: [
      { label: "Travel", value: "160 mm" },
      { label: "Stanchions", value: "36 mm" },
      { label: "Damper", value: "TTX18" },
      { label: "Air spring", value: "Three-chamber" },
      { label: "Axle", value: "15×110 Boost" },
      { label: "Brake mount", value: "Post mount, 180 mm native" },
    ],
    summary: "A motorsport-derived fork prized for traction and composure.",
    pros: ["Superb traction on rough ground", "Very consistent damping"],
    cons: ["Heaviest in its class", "Fewer service centres"],
    visual: { stanchion: "gold" },
  },
  {
    id: "rockshox-sid-sl-ultimate",
    category: "fork",
    disciplines: ["mtb"],
    brand: "RockShox",
    model: "SID SL Ultimate",
    priceEur: 1019,
    weightG: 1370,
    tier: 5,
    ratings: { performance: 9, comfort: 6, durability: 7.5, climbing: 10, descending: 6 },
    maintenance: "medium",
    compat: { wheelSize: "29", travelMm: 100, maxTireMm: 61, brakeMount: "post-mount", minRotorMm: 160 },
    specs: [
      { label: "Travel", value: "100 mm" },
      { label: "Stanchions", value: "32 mm" },
      { label: "Damper", value: "Race Day 2" },
      { label: "Axle", value: "15×110 Boost" },
      { label: "Brake mount", value: "Post mount, 160 mm native" },
    ],
    summary: "A featherweight cross-country race fork.",
    pros: ["Lightest fork in the catalog", "Firm, efficient lockout"],
    cons: ["Flexes under aggressive riding", "Only for XC frames"],
    visual: { stanchion: "black" },
  },
  {
    id: "rockshox-zeb-ultimate",
    category: "fork",
    disciplines: ["mtb"],
    brand: "RockShox",
    model: "ZEB Ultimate",
    priceEur: 1099,
    weightG: 2250,
    tier: 5,
    ratings: { performance: 9, comfort: 9, durability: 9, climbing: 6, descending: 10 },
    maintenance: "medium",
    compat: { wheelSize: "29", travelMm: 170, maxTireMm: 71, brakeMount: "post-mount", minRotorMm: 200 },
    specs: [
      { label: "Travel", value: "170 mm" },
      { label: "Stanchions", value: "38 mm" },
      { label: "Damper", value: "Charger 3" },
      { label: "Axle", value: "15×110 Boost" },
      { label: "Brake mount", value: "Post mount, 200 mm native" },
    ],
    summary: "A stiff, long-travel enduro fork for aggressive riders.",
    pros: ["Very stiff 38 mm chassis", "Handles big hits calmly"],
    cons: ["Heavy", "Requires ≥200 mm front rotor"],
    visual: { stanchion: "black" },
  },

  // ─── Wheels ──────────────────────────────────────────────────────────────
  {
    id: "dt-xrc-1200",
    category: "wheels",
    disciplines: ["mtb"],
    brand: "DT Swiss",
    model: "XRC 1200 Spline 25",
    priceEur: 1990,
    weightG: 1290,
    tier: 5,
    ratings: { performance: 10, comfort: 6.5, durability: 7, climbing: 10, descending: 6 },
    maintenance: "low",
    compat: { wheelSize: "29", freehubOptions: ["XD", "MicroSpline", "HG"] },
    specs: [
      { label: "Rim", value: "Carbon, 25 mm inner width" },
      { label: "Hubs", value: "240 EXP, Ratchet" },
      { label: "Weight", value: "≈1,290 g (set)" },
      { label: "Freehub", value: "XD / Micro Spline / HG" },
    ],
    summary: "An ultralight carbon race wheelset for cross-country.",
    pros: ["Very low rotating weight", "Reliable 240 hubs"],
    cons: ["Narrow rim for trail tires", "Expensive"],
    visual: { rimDepthMm: 24, color: "#111" },
  },
  {
    id: "dt-xm-1700",
    category: "wheels",
    disciplines: ["mtb"],
    brand: "DT Swiss",
    model: "XM 1700 Spline 30",
    priceEur: 749,
    weightG: 1850,
    tier: 3,
    ratings: { performance: 7.5, comfort: 7.5, durability: 9, climbing: 7, descending: 7.5 },
    maintenance: "low",
    compat: { wheelSize: "29", freehubOptions: ["XD", "MicroSpline", "HG"] },
    specs: [
      { label: "Rim", value: "Aluminium, 30 mm inner width" },
      { label: "Hubs", value: "370, Ratchet LN" },
      { label: "Weight", value: "≈1,850 g (set)" },
      { label: "Freehub", value: "XD / Micro Spline / HG" },
    ],
    summary: "A durable aluminium trail wheelset with an excellent price/performance ratio.",
    pros: ["Robust and easy to service", "Good value"],
    cons: ["Heavier than carbon options"],
    visual: { rimDepthMm: 20, color: "#1a1a1a" },
  },
  {
    id: "reserve-30-sl",
    category: "wheels",
    disciplines: ["mtb"],
    brand: "Reserve",
    model: "30|SL Carbon, DT 350",
    priceEur: 1799,
    weightG: 1640,
    tier: 5,
    ratings: { performance: 9, comfort: 8, durability: 9, climbing: 8.5, descending: 8.5 },
    maintenance: "low",
    compat: { wheelSize: "29", freehubOptions: ["XD", "MicroSpline", "HG"] },
    specs: [
      { label: "Rim", value: "Carbon, 30 mm inner width" },
      { label: "Hubs", value: "DT Swiss 350" },
      { label: "Weight", value: "≈1,640 g (set)" },
      { label: "Warranty", value: "Lifetime" },
    ],
    summary: "Light, strong carbon trail wheels with a lifetime warranty.",
    pros: ["Saves weight over aluminium", "Lifetime warranty"],
    cons: ["Firmer feel than aluminium rims"],
    visual: { rimDepthMm: 28, color: "#111" },
  },
  {
    id: "dt-ex-1700",
    category: "wheels",
    disciplines: ["mtb"],
    brand: "DT Swiss",
    model: "EX 1700 Spline 30",
    priceEur: 849,
    weightG: 2010,
    tier: 3,
    ratings: { performance: 7.5, comfort: 8, durability: 9.5, climbing: 6.5, descending: 8.5 },
    maintenance: "low",
    compat: { wheelSize: "29", freehubOptions: ["XD", "MicroSpline", "HG"] },
    specs: [
      { label: "Rim", value: "Aluminium, 30 mm inner width, enduro" },
      { label: "Hubs", value: "350" },
      { label: "Weight", value: "≈2,010 g (set)" },
    ],
    summary: "A tough enduro wheelset built for big hits.",
    pros: ["Very durable", "Serviceable 350 hubs"],
    cons: ["Heavy for trail or XC"],
    visual: { rimDepthMm: 22, color: "#1a1a1a" },
  },

  // ─── Tires (pair) ────────────────────────────────────────────────────────
  {
    id: "maxxis-rekon-race-24",
    category: "tires",
    disciplines: ["mtb"],
    brand: "Maxxis",
    model: "Rekon Race 29×2.4 EXO TR (pair)",
    priceEur: 120,
    weightG: 1640,
    tier: 4,
    ratings: { performance: 8.5, comfort: 6.5, durability: 6.5, climbing: 9, descending: 5.5 },
    maintenance: "low",
    compat: { wheelSize: "29", tireWidthMm: 61 },
    specs: [
      { label: "Size", value: '29×2.40"' },
      { label: "Casing", value: "EXO, tubeless ready" },
      { label: "Use", value: "XC / fast trail" },
    ],
    summary: "A fast-rolling semi-slick tire for racing and hardpack.",
    pros: ["Low rolling resistance", "Light"],
    cons: ["Limited grip in mud and loose corners"],
  },
  {
    id: "schwalbe-racing-ray-ralph",
    category: "tires",
    disciplines: ["mtb"],
    brand: "Schwalbe",
    model: "Racing Ray / Racing Ralph 29×2.35 Super Race",
    priceEur: 130,
    weightG: 1360,
    tier: 5,
    ratings: { performance: 9.5, comfort: 6, durability: 5, climbing: 10, descending: 5 },
    maintenance: "low",
    compat: { wheelSize: "29", tireWidthMm: 60 },
    specs: [
      { label: "Size", value: '29×2.35"' },
      { label: "Casing", value: "Super Race" },
      { label: "Use", value: "XC race" },
    ],
    summary: "A race-day tire combo for minimal weight and maximum speed.",
    pros: ["Very light", "Fast rolling"],
    cons: ["Thin casing is prone to cuts"],
  },
  {
    id: "maxxis-dissector-24",
    category: "tires",
    disciplines: ["mtb"],
    brand: "Maxxis",
    model: "Dissector 29×2.4 EXO+ (pair)",
    priceEur: 140,
    weightG: 1900,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7.5, durability: 7.5, climbing: 8, descending: 8 },
    maintenance: "low",
    compat: { wheelSize: "29", tireWidthMm: 61 },
    specs: [
      { label: "Size", value: '29×2.40"' },
      { label: "Casing", value: "EXO+, tubeless ready" },
      { label: "Use", value: "Trail" },
    ],
    summary: "A trail tire that balances grip with rolling speed.",
    pros: ["Good cornering grip", "Rolls faster than full enduro treads"],
    cons: ["Not a mud tire"],
  },
  {
    id: "maxxis-dhf-dhr-25",
    category: "tires",
    disciplines: ["mtb"],
    brand: "Maxxis",
    model: "Minion DHF 2.5 / DHR II 2.4 EXO+",
    priceEur: 150,
    weightG: 2280,
    tier: 4,
    ratings: { performance: 8, comfort: 8.5, durability: 8.5, climbing: 6.5, descending: 9.5 },
    maintenance: "low",
    compat: { wheelSize: "29", tireWidthMm: 64 },
    specs: [
      { label: "Size", value: '29×2.50" / 29×2.40"' },
      { label: "Casing", value: "EXO+, MaxxTerra" },
      { label: "Use", value: "Trail / enduro" },
    ],
    summary: "The classic grippy trail/enduro combination.",
    pros: ["Predictable cornering", "Strong braking traction"],
    cons: ["Heavier, slower on climbs"],
  },
  {
    id: "conti-kryptotal-enduro",
    category: "tires",
    disciplines: ["mtb"],
    brand: "Continental",
    model: "Kryptotal Fr/Re 29×2.4 Enduro (pair)",
    priceEur: 150,
    weightG: 2440,
    tier: 4,
    ratings: { performance: 8, comfort: 8.5, durability: 9, climbing: 6, descending: 9.5 },
    maintenance: "low",
    compat: { wheelSize: "29", tireWidthMm: 61 },
    specs: [
      { label: "Size", value: '29×2.40"' },
      { label: "Casing", value: "Enduro, Soft compound" },
      { label: "Use", value: "Enduro" },
    ],
    summary: "Robust enduro tires with a strong casing.",
    pros: ["Excellent puncture resistance", "Very grippy compound"],
    cons: ["Heavy"],
  },

  // ─── Groupset (shifter + rear derailleur) ────────────────────────────────
  {
    id: "sram-xx-sl-transmission",
    category: "groupset",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "XX SL Eagle Transmission AXS",
    priceEur: 1100,
    weightG: 430,
    tier: 5,
    ratings: { performance: 10, comfort: 7, durability: 9, climbing: 9.5, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission", speeds: 12, requiresUdh: true, electronic: true },
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Shifting", value: "Wireless electronic (AXS)" },
      { label: "Mount", value: "Full Mount (UDH frames only)" },
    ],
    summary: "SRAM's lightest wireless drivetrain, mounted directly to the frame.",
    pros: ["Shifts under load reliably", "Hangerless design is very robust"],
    cons: ["Requires a UDH frame", "Batteries need charging"],
  },
  {
    id: "sram-x0-transmission",
    category: "groupset",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "X0 Eagle Transmission AXS",
    priceEur: 790,
    weightG: 520,
    tier: 4,
    ratings: { performance: 9, comfort: 7, durability: 9.5, climbing: 9, descending: 8.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission", speeds: 12, requiresUdh: true, electronic: true },
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Shifting", value: "Wireless electronic (AXS)" },
      { label: "Mount", value: "Full Mount (UDH frames only)" },
    ],
    summary: "Transmission performance with sturdier, more affordable parts.",
    pros: ["Extremely robust derailleur", "Precise shifting"],
    cons: ["Requires a UDH frame"],
  },
  {
    id: "shimano-xtr-m9100",
    category: "groupset",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "XTR M9100 12-speed",
    priceEur: 560,
    weightG: 330,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 8, climbing: 9.5, descending: 8 },
    maintenance: "medium",
    compat: { drivetrain: "shimano-mtb-12", speeds: 12 },
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Shifting", value: "Mechanical, cable" },
      { label: "Mount", value: "Standard derailleur hanger" },
    ],
    summary: "Shimano's lightest mechanical mountain bike groupset.",
    pros: ["Very light", "Crisp mechanical shifting"],
    cons: ["Cable needs periodic adjustment"],
  },
  {
    id: "shimano-xt-m8100",
    category: "groupset",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "Deore XT M8100 12-speed",
    priceEur: 290,
    weightG: 400,
    tier: 3,
    ratings: { performance: 8.5, comfort: 7, durability: 8.5, climbing: 8.5, descending: 8 },
    maintenance: "medium",
    compat: { drivetrain: "shimano-mtb-12", speeds: 12 },
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Shifting", value: "Mechanical, cable" },
    ],
    summary: "A workhorse groupset with near-XTR performance at a much lower price.",
    pros: ["Excellent value", "Easy to service anywhere"],
    cons: ["Slightly heavier than XTR"],
  },
  {
    id: "sram-gx-eagle",
    category: "groupset",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "GX Eagle 12-speed (mechanical)",
    priceEur: 220,
    weightG: 410,
    tier: 3,
    ratings: { performance: 7.5, comfort: 7, durability: 7.5, climbing: 8, descending: 7.5 },
    maintenance: "medium",
    compat: { drivetrain: "sram-eagle", speeds: 12 },
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Shifting", value: "Mechanical, cable" },
    ],
    summary: "A reliable, affordable Eagle drivetrain for any frame with a hanger.",
    pros: ["Affordable", "Works on non-UDH frames"],
    cons: ["Shifting under load is less refined than Transmission"],
  },

  // ─── Cranksets ───────────────────────────────────────────────────────────
  {
    id: "sram-xx-sl-crank",
    category: "crankset",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "XX SL Eagle Transmission Crankset, 32T",
    priceEur: 600,
    weightG: 440,
    tier: 5,
    ratings: { performance: 10, comfort: 7, durability: 8, climbing: 10, descending: 7.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission" },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Chainring", value: "32T T-Type" },
      { label: "Spindle", value: "DUB" },
    ],
    summary: "An ultralight carbon crank with a T-Type chainring.",
    pros: ["Very light", "Stiff"],
    cons: ["Expensive"],
  },
  {
    id: "sram-x0-crank",
    category: "crankset",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "X0 Eagle Transmission Crankset, 32T",
    priceEur: 430,
    weightG: 530,
    tier: 4,
    ratings: { performance: 9, comfort: 7, durability: 8.5, climbing: 9, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission" },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Chainring", value: "32T T-Type" },
      { label: "Spindle", value: "DUB" },
    ],
    summary: "Carbon Transmission crank for trail and enduro use.",
    pros: ["Good strength-to-weight", "T-Type ring"],
    cons: ["Heavier than XX SL"],
  },
  {
    id: "shimano-xtr-crank",
    category: "crankset",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "XTR FC-M9100-1, 32T",
    priceEur: 499,
    weightG: 520,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 8.5, climbing: 9.5, descending: 7.5 },
    maintenance: "low",
    compat: { drivetrain: "shimano-mtb-12" },
    specs: [
      { label: "Material", value: "Aluminium, Hollowtech II" },
      { label: "Chainring", value: "32T" },
      { label: "Spindle", value: "24 mm Hollowtech II" },
    ],
    summary: "Shimano's lightest mountain bike crankset.",
    pros: ["Light and stiff", "Very durable chainring"],
    cons: ["Expensive for aluminium"],
  },
  {
    id: "shimano-xt-crank",
    category: "crankset",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "Deore XT FC-M8100-1, 32T",
    priceEur: 229,
    weightG: 620,
    tier: 3,
    ratings: { performance: 8.5, comfort: 7, durability: 9, climbing: 8.5, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "shimano-mtb-12" },
    specs: [
      { label: "Material", value: "Aluminium, Hollowtech II" },
      { label: "Chainring", value: "32T" },
    ],
    summary: "A strong, affordable crankset.",
    pros: ["Great value", "Durable"],
    cons: ["Heavier than XTR"],
  },
  {
    id: "sram-gx-crank",
    category: "crankset",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "GX Eagle DUB, 32T",
    priceEur: 169,
    weightG: 650,
    tier: 3,
    ratings: { performance: 7.5, comfort: 7, durability: 8.5, climbing: 8, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "sram-eagle" },
    specs: [
      { label: "Material", value: "Aluminium" },
      { label: "Chainring", value: "32T X-Sync 2" },
      { label: "Spindle", value: "DUB" },
    ],
    summary: "An affordable Eagle crankset.",
    pros: ["Affordable", "Robust"],
    cons: ["Heavier"],
  },

  // ─── Cassettes ───────────────────────────────────────────────────────────
  {
    id: "sram-xs1299",
    category: "cassette",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "XX Eagle Transmission XS-1299, 10–52T",
    priceEur: 549,
    weightG: 380,
    tier: 5,
    ratings: { performance: 10, comfort: 7, durability: 8.5, climbing: 10, descending: 7.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission", speeds: 12, freehub: "XD" },
    specs: [
      { label: "Range", value: "10–52T (520%)" },
      { label: "Freehub", value: "XD" },
      { label: "Speeds", value: "12" },
    ],
    summary: "A lightweight T-Type cassette.",
    pros: ["Very light", "Wide range"],
    cons: ["Expensive to replace"],
  },
  {
    id: "sram-xs1295",
    category: "cassette",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "X0 Eagle Transmission XS-1295, 10–52T",
    priceEur: 399,
    weightG: 450,
    tier: 4,
    ratings: { performance: 9, comfort: 7, durability: 9, climbing: 9, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission", speeds: 12, freehub: "XD" },
    specs: [
      { label: "Range", value: "10–52T (520%)" },
      { label: "Freehub", value: "XD" },
      { label: "Speeds", value: "12" },
    ],
    summary: "Durable T-Type cassette for trail riding.",
    pros: ["Durable", "Wide range"],
    cons: ["Heavier than XS-1299"],
  },
  {
    id: "shimano-xtr-cassette",
    category: "cassette",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "XTR CS-M9100-12, 10–51T",
    priceEur: 339,
    weightG: 370,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 8, climbing: 9.5, descending: 7.5 },
    maintenance: "low",
    compat: { drivetrain: "shimano-mtb-12", speeds: 12, freehub: "MicroSpline" },
    specs: [
      { label: "Range", value: "10–51T" },
      { label: "Freehub", value: "Micro Spline" },
      { label: "Speeds", value: "12" },
    ],
    summary: "Light titanium/aluminium Shimano cassette.",
    pros: ["Light", "Smooth Hyperglide+ shifting"],
    cons: ["Pricey wear item"],
  },
  {
    id: "shimano-xt-cassette",
    category: "cassette",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "Deore XT CS-M8100-12, 10–51T",
    priceEur: 139,
    weightG: 470,
    tier: 3,
    ratings: { performance: 8.5, comfort: 7, durability: 9, climbing: 8.5, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "shimano-mtb-12", speeds: 12, freehub: "MicroSpline" },
    specs: [
      { label: "Range", value: "10–51T" },
      { label: "Freehub", value: "Micro Spline" },
      { label: "Speeds", value: "12" },
    ],
    summary: "Durable, affordable 12-speed cassette.",
    pros: ["Great value", "Long lasting"],
    cons: ["100 g heavier than XTR"],
  },
  {
    id: "sram-xg1275",
    category: "cassette",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "GX Eagle XG-1275, 10–52T",
    priceEur: 169,
    weightG: 450,
    tier: 3,
    ratings: { performance: 7.5, comfort: 7, durability: 8, climbing: 8, descending: 7.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-eagle", speeds: 12, freehub: "XD" },
    specs: [
      { label: "Range", value: "10–52T" },
      { label: "Freehub", value: "XD" },
      { label: "Speeds", value: "12" },
    ],
    summary: "Eagle cassette for mechanical GX drivetrains.",
    pros: ["Affordable", "Wide range"],
    cons: ["Not T-Type"],
  },

  // ─── Chains ──────────────────────────────────────────────────────────────
  {
    id: "sram-t-type-chain",
    category: "chain",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "XX T-Type Flattop Chain",
    priceEur: 99,
    weightG: 250,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 9, climbing: 9, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "sram-transmission", speeds: 12, chain: "t-type" },
    specs: [
      { label: "Speeds", value: "12" },
      { label: "Standard", value: "T-Type Flattop" },
    ],
    summary: "The required chain for Eagle Transmission drivetrains.",
    pros: ["Quiet and durable", "Required for Transmission"],
    cons: ["Only for T-Type drivetrains"],
  },
  {
    id: "sram-gx-chain",
    category: "chain",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "GX Eagle Chain",
    priceEur: 35,
    weightG: 265,
    tier: 3,
    ratings: { performance: 7.5, comfort: 7, durability: 7.5, climbing: 8, descending: 7.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-eagle", speeds: 12, chain: "sram-eagle" },
    specs: [{ label: "Speeds", value: "12" }],
    summary: "Standard 12-speed Eagle chain.",
    pros: ["Affordable"],
    cons: ["Not compatible with T-Type"],
  },
  {
    id: "shimano-xtr-chain",
    category: "chain",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "XTR CN-M9100",
    priceEur: 69,
    weightG: 245,
    tier: 5,
    ratings: { performance: 9, comfort: 7, durability: 8.5, climbing: 9, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "shimano-mtb-12", speeds: 12, chain: "shimano-hg" },
    specs: [{ label: "Speeds", value: "12" }],
    summary: "Shimano's premium 12-speed chain.",
    pros: ["Light", "Smooth"],
    cons: ["Pricier than XT"],
  },
  {
    id: "shimano-xt-chain",
    category: "chain",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "Deore XT CN-M8100",
    priceEur: 42,
    weightG: 252,
    tier: 3,
    ratings: { performance: 8.5, comfort: 7, durability: 8.5, climbing: 8.5, descending: 8 },
    maintenance: "low",
    compat: { drivetrain: "shimano-mtb-12", speeds: 12, chain: "shimano-hg" },
    specs: [{ label: "Speeds", value: "12" }],
    summary: "Durable, affordable Shimano 12-speed chain.",
    pros: ["Good value"],
    cons: [],
  },

  // ─── Brakes (set incl. rotors) ───────────────────────────────────────────
  {
    id: "sram-level-ultimate",
    category: "brakes",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "Level Ultimate Stealth 2-piston",
    priceEur: 560,
    weightG: 620,
    tier: 5,
    ratings: { performance: 8, comfort: 7, durability: 8, climbing: 9.5, descending: 6 },
    maintenance: "medium",
    compat: { brakeSystem: "sram", brakeMounts: ["post-mount", "flat-mount"], rotorsMm: [160, 160] },
    specs: [
      { label: "Pistons", value: "2" },
      { label: "Rotors", value: "160 / 160 mm" },
      { label: "Caliper mount", value: "Post or flat mount versions" },
    ],
    summary: "Lightweight XC brakes.",
    pros: ["Very light", "Good modulation"],
    cons: ["Limited power for long descents"],
  },
  {
    id: "shimano-xtr-m9120",
    category: "brakes",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "XTR BR-M9120 4-piston",
    priceEur: 699,
    weightG: 780,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 8.5, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { brakeSystem: "shimano", brakeMounts: ["post-mount"], rotorsMm: [203, 180] },
    specs: [
      { label: "Pistons", value: "4" },
      { label: "Rotors", value: "203 / 180 mm" },
      { label: "Caliper mount", value: "Post mount" },
    ],
    summary: "Powerful, light Shimano trail brakes.",
    pros: ["Strong and consistent", "Mineral oil is easy to bleed"],
    cons: ["Bite point can wander on long descents"],
  },
  {
    id: "shimano-xt-m8120",
    category: "brakes",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "Deore XT BR-M8120 4-piston",
    priceEur: 329,
    weightG: 900,
    tier: 3,
    ratings: { performance: 9, comfort: 7.5, durability: 8.5, climbing: 8, descending: 9 },
    maintenance: "low",
    compat: { brakeSystem: "shimano", brakeMounts: ["post-mount"], rotorsMm: [203, 180] },
    specs: [
      { label: "Pistons", value: "4" },
      { label: "Rotors", value: "203 / 180 mm" },
      { label: "Caliper mount", value: "Post mount" },
    ],
    summary: "Near-XTR stopping power at half the price.",
    pros: ["Excellent value", "Strong bite"],
    cons: ["Heavier than XTR"],
  },
  {
    id: "sram-code-rsc",
    category: "brakes",
    disciplines: ["mtb"],
    brand: "SRAM",
    model: "Code RSC 4-piston",
    priceEur: 599,
    weightG: 1010,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 9, climbing: 7, descending: 9.5 },
    maintenance: "medium",
    compat: { brakeSystem: "sram", brakeMounts: ["post-mount"], rotorsMm: [200, 200] },
    specs: [
      { label: "Pistons", value: "4" },
      { label: "Rotors", value: "200 / 200 mm" },
      { label: "Caliper mount", value: "Post mount" },
    ],
    summary: "Enduro-grade brakes with excellent modulation.",
    pros: ["Very consistent on long descents", "Great modulation"],
    cons: ["Heavy", "DOT fluid"],
  },
  {
    id: "magura-mt7-pro",
    category: "brakes",
    disciplines: ["mtb"],
    brand: "Magura",
    model: "MT7 Pro 4-piston",
    priceEur: 549,
    weightG: 900,
    tier: 4,
    ratings: { performance: 9.5, comfort: 7.5, durability: 8, climbing: 7.5, descending: 9.5 },
    maintenance: "medium",
    compat: { brakeSystem: "magura", brakeMounts: ["post-mount"], rotorsMm: [203, 180] },
    specs: [
      { label: "Pistons", value: "4" },
      { label: "Rotors", value: "203 / 180 mm" },
      { label: "Caliper mount", value: "Post mount" },
    ],
    summary: "Among the most powerful trail brakes available.",
    pros: ["Huge power", "Tool-free reach adjustment"],
    cons: ["Carbotecture lever feel is divisive"],
  },
  {
    id: "hope-tech4-v4",
    category: "brakes",
    disciplines: ["mtb"],
    brand: "Hope",
    model: "Tech 4 V4",
    priceEur: 640,
    weightG: 1020,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 9.5, climbing: 7, descending: 9.5 },
    maintenance: "low",
    compat: { brakeSystem: "hope", brakeMounts: ["post-mount"], rotorsMm: [200, 200] },
    specs: [
      { label: "Pistons", value: "4" },
      { label: "Rotors", value: "200 / 200 mm vented" },
      { label: "Caliper mount", value: "Post mount" },
    ],
    summary: "UK-made, fully serviceable enduro brakes.",
    pros: ["Every part is serviceable", "Excellent heat management"],
    cons: ["Heavy"],
  },

  // ─── Handlebars ──────────────────────────────────────────────────────────
  {
    id: "raceface-atlas-35",
    category: "handlebar",
    disciplines: ["mtb"],
    brand: "Race Face",
    model: "Atlas 35 Alloy, 800 mm",
    priceEur: 69,
    weightG: 350,
    tier: 3,
    ratings: { performance: 7.5, comfort: 7, durability: 9, climbing: 7, descending: 8.5 },
    maintenance: "low",
    compat: { barClampMm: 35 },
    specs: [
      { label: "Material", value: "7050 aluminium" },
      { label: "Clamp", value: "35 mm" },
      { label: "Width", value: "800 mm" },
    ],
    summary: "A strong aluminium trail bar.",
    pros: ["Robust", "Affordable"],
    cons: ["Heavier than carbon"],
  },
  {
    id: "oneup-carbon-35",
    category: "handlebar",
    disciplines: ["mtb"],
    brand: "OneUp",
    model: "Carbon Handlebar 35, 800 mm",
    priceEur: 159,
    weightG: 225,
    tier: 4,
    ratings: { performance: 8.5, comfort: 9, durability: 8.5, climbing: 8, descending: 8.5 },
    maintenance: "low",
    compat: { barClampMm: 35 },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Clamp", value: "35 mm" },
      { label: "Width", value: "800 mm" },
    ],
    summary: "A carbon bar designed with vertical compliance to reduce hand fatigue.",
    pros: ["Noticeably more comfortable", "Saves ~125 g over alloy"],
    cons: ["Carbon needs torque-wrench care"],
  },
  {
    id: "renthal-fatbar-carbon-35",
    category: "handlebar",
    disciplines: ["mtb"],
    brand: "Renthal",
    model: "FatBar Carbon 35, 800 mm",
    priceEur: 169,
    weightG: 230,
    tier: 5,
    ratings: { performance: 9, comfort: 8.5, durability: 9, climbing: 8, descending: 9 },
    maintenance: "low",
    compat: { barClampMm: 35 },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Clamp", value: "35 mm" },
    ],
    summary: "A stiff, precise carbon bar favoured by gravity riders.",
    pros: ["Very precise steering", "Light"],
    cons: ["Stiffer ride than OneUp"],
  },
  {
    id: "easton-ec90-sl-318",
    category: "handlebar",
    disciplines: ["mtb"],
    brand: "Easton",
    model: "EC90 SL Flat Bar 31.8, 740 mm",
    priceEur: 159,
    weightG: 170,
    tier: 5,
    ratings: { performance: 9, comfort: 7.5, durability: 7.5, climbing: 9.5, descending: 6.5 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Clamp", value: "31.8 mm" },
      { label: "Width", value: "740 mm" },
    ],
    summary: "An ultralight XC flat bar.",
    pros: ["Extremely light"],
    cons: ["Narrow for trail riding", "Needs a 31.8 mm stem"],
  },

  // ─── Stems ───────────────────────────────────────────────────────────────
  {
    id: "raceface-turbine-r-35",
    category: "stem",
    disciplines: ["mtb"],
    brand: "Race Face",
    model: "Turbine R 35, 40 mm",
    priceEur: 85,
    weightG: 125,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7, durability: 9, climbing: 7.5, descending: 8.5 },
    maintenance: "low",
    compat: { barClampMm: 35 },
    specs: [
      { label: "Clamp", value: "35 mm" },
      { label: "Length", value: "40 mm" },
    ],
    summary: "A light, stiff trail stem.",
    pros: ["Light", "Stiff"],
    cons: [],
  },
  {
    id: "renthal-apex-35",
    category: "stem",
    disciplines: ["mtb"],
    brand: "Renthal",
    model: "Apex 35, 50 mm",
    priceEur: 95,
    weightG: 135,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7, durability: 9.5, climbing: 7.5, descending: 9 },
    maintenance: "low",
    compat: { barClampMm: 35 },
    specs: [
      { label: "Clamp", value: "35 mm" },
      { label: "Length", value: "50 mm" },
    ],
    summary: "Precision-machined gravity stem.",
    pros: ["Very durable"],
    cons: [],
  },
  {
    id: "thomson-elite-x4-318",
    category: "stem",
    disciplines: ["mtb"],
    brand: "Thomson",
    model: "Elite X4 31.8, 70 mm",
    priceEur: 95,
    weightG: 130,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7, durability: 9.5, climbing: 9, descending: 7 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Clamp", value: "31.8 mm" },
      { label: "Length", value: "70 mm" },
    ],
    summary: "A classic XC stem for a stretched-out position.",
    pros: ["Bombproof", "Light"],
    cons: ["Long for modern trail geometry"],
  },

  // ─── Seatposts ───────────────────────────────────────────────────────────
  {
    id: "oneup-v3-dropper",
    category: "seatpost",
    disciplines: ["mtb"],
    brand: "OneUp",
    model: "V3 Dropper Post, 180 mm",
    priceEur: 259,
    weightG: 560,
    tier: 4,
    ratings: { performance: 8.5, comfort: 8, durability: 8.5, climbing: 7, descending: 9 },
    maintenance: "low",
    compat: { seatpostFits: ["30.9", "31.6", "34.9"] },
    specs: [
      { label: "Drop", value: "180 mm" },
      { label: "Diameters", value: "30.9 / 31.6 / 34.9 mm" },
      { label: "Actuation", value: "Cable" },
    ],
    summary: "A short-stack dropper that allows more drop in the same frame.",
    pros: ["Great value", "Easy to service"],
    cons: ["Cable routing needed"],
  },
  {
    id: "fox-transfer-factory",
    category: "seatpost",
    disciplines: ["mtb"],
    brand: "Fox",
    model: "Transfer Factory, 175 mm",
    priceEur: 459,
    weightG: 610,
    tier: 5,
    ratings: { performance: 8.5, comfort: 8, durability: 8.5, climbing: 7, descending: 9 },
    maintenance: "medium",
    compat: { seatpostFits: ["30.9", "31.6", "34.9"] },
    specs: [
      { label: "Drop", value: "175 mm" },
      { label: "Diameters", value: "30.9 / 31.6 / 34.9 mm" },
    ],
    summary: "Smooth, reliable dropper with Kashima finish.",
    pros: ["Very smooth action"],
    cons: ["Expensive"],
  },
  {
    id: "rockshox-reverb-axs",
    category: "seatpost",
    disciplines: ["mtb"],
    brand: "RockShox",
    model: "Reverb AXS, 170 mm",
    priceEur: 799,
    weightG: 680,
    tier: 5,
    ratings: { performance: 8.5, comfort: 8, durability: 8, climbing: 6.5, descending: 9 },
    maintenance: "medium",
    compat: { seatpostFits: ["30.9", "31.6", "34.9"], electronic: true },
    specs: [
      { label: "Drop", value: "170 mm" },
      { label: "Actuation", value: "Wireless (AXS)" },
    ],
    summary: "Wireless dropper — no cable to route.",
    pros: ["Clean, cable-free setup"],
    cons: ["Heavy and expensive", "Battery to charge"],
  },
  {
    id: "ritchey-wcs-carbon-316",
    category: "seatpost",
    disciplines: ["mtb"],
    brand: "Ritchey",
    model: "WCS Carbon Link Flexlogic (rigid)",
    priceEur: 169,
    weightG: 190,
    tier: 4,
    ratings: { performance: 9, comfort: 7.5, durability: 8, climbing: 10, descending: 4.5 },
    maintenance: "low",
    compat: { seatpostFits: ["27.2", "30.9", "31.6"] },
    specs: [
      { label: "Type", value: "Rigid carbon" },
      { label: "Diameters", value: "27.2 / 30.9 / 31.6 mm" },
    ],
    summary: "A light rigid seatpost for XC racing.",
    pros: ["Saves ~350 g over a dropper"],
    cons: ["No drop — harder on steep descents"],
  },

  // ─── Saddles ─────────────────────────────────────────────────────────────
  {
    id: "specialized-power-pro",
    category: "saddle",
    disciplines: ["mtb", "road"],
    brand: "Specialized",
    model: "Power Pro Elaston",
    priceEur: 169,
    weightG: 225,
    tier: 4,
    ratings: { performance: 8.5, comfort: 8.5, durability: 8, climbing: 8.5, descending: 7.5 },
    maintenance: "low",
    compat: {},
    specs: [
      { label: "Rails", value: "Titanium" },
      { label: "Shape", value: "Short nose, cut-out" },
    ],
    summary: "A short-nose saddle designed to relieve soft-tissue pressure.",
    pros: ["Comfortable in an aggressive position"],
    cons: ["Short shape doesn't suit everyone"],
  },
  {
    id: "ergon-sm-enduro-pro",
    category: "saddle",
    disciplines: ["mtb"],
    brand: "Ergon",
    model: "SM Enduro Pro",
    priceEur: 139,
    weightG: 290,
    tier: 4,
    ratings: { performance: 8, comfort: 9, durability: 8.5, climbing: 7.5, descending: 8.5 },
    maintenance: "low",
    compat: {},
    specs: [{ label: "Rails", value: "Titanium" }],
    summary: "Shaped for moving around the bike on descents.",
    pros: ["Very comfortable", "Tapered shape for descending"],
    cons: ["Heavier than race saddles"],
  },
  {
    id: "wtb-volt",
    category: "saddle",
    disciplines: ["mtb"],
    brand: "WTB",
    model: "Volt Chromoly",
    priceEur: 59,
    weightG: 285,
    tier: 2,
    ratings: { performance: 7, comfort: 8, durability: 8, climbing: 7, descending: 7.5 },
    maintenance: "low",
    compat: {},
    specs: [{ label: "Rails", value: "Chromoly" }],
    summary: "A popular, affordable all-round saddle.",
    pros: ["Affordable", "Comfortable padding"],
    cons: ["Heavier rails"],
  },
  {
    id: "selle-italia-slr-boost",
    category: "saddle",
    disciplines: ["mtb", "road"],
    brand: "Selle Italia",
    model: "SLR Boost Superflow",
    priceEur: 159,
    weightG: 190,
    tier: 5,
    ratings: { performance: 9, comfort: 7, durability: 7.5, climbing: 9, descending: 6.5 },
    maintenance: "low",
    compat: {},
    specs: [{ label: "Rails", value: "Titanium" }],
    summary: "A light race saddle with a pressure-relief channel.",
    pros: ["Light"],
    cons: ["Firm padding"],
  },

  // ─── Pedals ──────────────────────────────────────────────────────────────
  {
    id: "shimano-xtr-pd-m9100",
    category: "pedals",
    disciplines: ["mtb"],
    brand: "Shimano",
    model: "XTR PD-M9100 SPD",
    priceEur: 189,
    weightG: 310,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 9, climbing: 9.5, descending: 7 },
    maintenance: "low",
    compat: { pedalType: "clipless-spd" },
    specs: [
      { label: "Type", value: "Clipless SPD" },
      { label: "Weight", value: "≈310 g (pair)" },
    ],
    summary: "Light, reliable clipless XC pedals.",
    pros: ["Light", "Very durable bearings"],
    cons: ["Small platform"],
  },
  {
    id: "crankbrothers-stamp-7",
    category: "pedals",
    disciplines: ["mtb"],
    brand: "Crankbrothers",
    model: "Stamp 7 Flat",
    priceEur: 149,
    weightG: 380,
    tier: 4,
    ratings: { performance: 8, comfort: 8.5, durability: 8.5, climbing: 6.5, descending: 9.5 },
    maintenance: "low",
    compat: { pedalType: "flat" },
    specs: [{ label: "Type", value: "Flat, aluminium" }],
    summary: "A thin, grippy flat pedal in two platform sizes.",
    pros: ["Excellent grip", "Confidence on technical descents"],
    cons: ["Less efficient than clipless on climbs"],
  },
  {
    id: "time-atac-xc8",
    category: "pedals",
    disciplines: ["mtb"],
    brand: "Time",
    model: "ATAC XC 8",
    priceEur: 129,
    weightG: 320,
    tier: 4,
    ratings: { performance: 9, comfort: 7.5, durability: 8, climbing: 9, descending: 7 },
    maintenance: "low",
    compat: { pedalType: "clipless-spd" },
    specs: [{ label: "Type", value: "Clipless (ATAC)" }],
    summary: "Mud-shedding clipless pedals with generous float.",
    pros: ["Clears mud well", "Knee-friendly float"],
    cons: ["Proprietary cleats"],
  },
  {
    id: "oneup-composite-flat",
    category: "pedals",
    disciplines: ["mtb"],
    brand: "OneUp",
    model: "Composite Flat",
    priceEur: 55,
    weightG: 355,
    tier: 2,
    ratings: { performance: 7, comfort: 8, durability: 8, climbing: 6, descending: 8.5 },
    maintenance: "low",
    compat: { pedalType: "flat" },
    specs: [{ label: "Type", value: "Flat, composite" }],
    summary: "Affordable, grippy composite flat pedals.",
    pros: ["Cheap", "Grippy"],
    cons: ["Thicker platform"],
  },
];
