import type { BikeComponent } from "../types";

/**
 * Road bike sample catalog. Same caveats as the MTB catalog: real product
 * names, indicative prices and approximate weights.
 *
 * Road framesets ship with a frame-specific fork (and often a proprietary
 * seatpost), which is modelled with `onlyFitsFrames` / `seatpostFit`.
 */
export const ROAD_COMPONENTS: BikeComponent[] = [
  // ─── Frames ──────────────────────────────────────────────────────────────
  {
    id: "specialized-tarmac-sl8",
    category: "frame",
    disciplines: ["road"],
    brand: "Specialized",
    model: "S-Works Tarmac SL8 Frameset",
    priceEur: 5500,
    weightG: 685,
    tier: 5,
    ratings: { performance: 10, comfort: 7, durability: 7.5, climbing: 9.5, descending: 9 },
    maintenance: "medium",
    compat: { wheelSize: "700c", maxTireMm: 32, brakeMount: "flat-mount", seatpostFit: "tarmac-sl8", travelMm: 0 },
    specs: [
      { label: "Material", value: "FACT 12r carbon" },
      { label: "Max tire", value: "32 mm" },
      { label: "Brake mount", value: "Flat mount" },
      { label: "Seatpost", value: "Frame-specific" },
    ],
    summary: "An aero race frame that is also among the lightest in its class.",
    pros: ["Aero and light", "Race-proven geometry"],
    cons: ["Frame-specific seatpost", "Firm ride"],
    visual: { color: "#101214", accent: "#c7ccd1", shape: "road-race" },
  },
  {
    id: "specialized-aethos",
    category: "frame",
    disciplines: ["road"],
    brand: "Specialized",
    model: "S-Works Aethos Frameset",
    priceEur: 4500,
    weightG: 585,
    tier: 5,
    ratings: { performance: 9, comfort: 8.5, durability: 7.5, climbing: 10, descending: 8 },
    maintenance: "low",
    compat: { wheelSize: "700c", maxTireMm: 32, brakeMount: "flat-mount", seatpostFit: "27.2", travelMm: 0 },
    specs: [
      { label: "Material", value: "FACT 12r carbon" },
      { label: "Max tire", value: "32 mm" },
      { label: "Brake mount", value: "Flat mount" },
      { label: "Seatpost", value: "Round 27.2 mm" },
    ],
    summary: "An ultralight, non-aero frame focused on ride quality.",
    pros: ["Extremely light", "Standard 27.2 seatpost", "Lively ride"],
    cons: ["Less aero than the Tarmac"],
    visual: { color: "#5c6b5a", accent: "#e8e4d8", shape: "road-light" },
  },
  {
    id: "canyon-aeroad-cfr",
    category: "frame",
    disciplines: ["road"],
    brand: "Canyon",
    model: "Aeroad CFR Frameset",
    priceEur: 3999,
    weightG: 915,
    tier: 5,
    ratings: { performance: 10, comfort: 6.5, durability: 7.5, climbing: 8, descending: 9.5 },
    maintenance: "medium",
    compat: { wheelSize: "700c", maxTireMm: 30, brakeMount: "flat-mount", seatpostFit: "aeroad", travelMm: 0 },
    specs: [
      { label: "Material", value: "CFR carbon" },
      { label: "Max tire", value: "30 mm" },
      { label: "Brake mount", value: "Flat mount" },
      { label: "Seatpost", value: "Frame-specific aero" },
    ],
    summary: "A pure aero race frame for flat and rolling terrain.",
    pros: ["Very fast on the flat", "Great value for a pro-level frame"],
    cons: ["Heavier than climbing frames", "Firm ride"],
    visual: { color: "#1b2330", accent: "#6f86a6", shape: "road-race" },
  },

  // ─── Forks (frameset-specific) ───────────────────────────────────────────
  {
    id: "tarmac-sl8-fork",
    category: "fork",
    disciplines: ["road"],
    brand: "Specialized",
    model: "Tarmac SL8 FACT Carbon Fork",
    priceEur: 0,
    weightG: 380,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 8, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { wheelSize: "700c", travelMm: 0, maxTireMm: 32, brakeMount: "flat-mount", minRotorMm: 140, onlyFitsFrames: ["specialized-tarmac-sl8"] },
    specs: [
      { label: "Material", value: "FACT carbon" },
      { label: "Axle", value: "12×100 thru-axle" },
    ],
    summary: "Included with the Tarmac SL8 frameset.",
    pros: ["Matched to the frame's aero profile"],
    cons: ["Only fits the Tarmac SL8"],
    includedWith: "S-Works Tarmac SL8 Frameset",
  },
  {
    id: "aethos-fork",
    category: "fork",
    disciplines: ["road"],
    brand: "Specialized",
    model: "Aethos FACT Carbon Fork",
    priceEur: 0,
    weightG: 280,
    tier: 5,
    ratings: { performance: 9, comfort: 8, durability: 8, climbing: 10, descending: 8 },
    maintenance: "low",
    compat: { wheelSize: "700c", travelMm: 0, maxTireMm: 32, brakeMount: "flat-mount", minRotorMm: 140, onlyFitsFrames: ["specialized-aethos"] },
    specs: [
      { label: "Material", value: "FACT carbon" },
      { label: "Axle", value: "12×100 thru-axle" },
    ],
    summary: "Included with the Aethos frameset.",
    pros: ["Very light"],
    cons: ["Only fits the Aethos"],
    includedWith: "S-Works Aethos Frameset",
  },
  {
    id: "aeroad-fork",
    category: "fork",
    disciplines: ["road"],
    brand: "Canyon",
    model: "Aeroad CFR Fork",
    priceEur: 0,
    weightG: 410,
    tier: 5,
    ratings: { performance: 9.5, comfort: 6.5, durability: 8, climbing: 8, descending: 9.5 },
    maintenance: "low",
    compat: { wheelSize: "700c", travelMm: 0, maxTireMm: 30, brakeMount: "flat-mount", minRotorMm: 140, onlyFitsFrames: ["canyon-aeroad-cfr"] },
    specs: [
      { label: "Material", value: "CFR carbon" },
      { label: "Axle", value: "12×100 thru-axle" },
    ],
    summary: "Included with the Aeroad CFR frameset.",
    pros: ["Aero profile"],
    cons: ["Only fits the Aeroad"],
    includedWith: "Aeroad CFR Frameset",
  },

  // ─── Wheels ──────────────────────────────────────────────────────────────
  {
    id: "roval-rapide-clx-ii",
    category: "wheels",
    disciplines: ["road"],
    brand: "Roval",
    model: "Rapide CLX II",
    priceEur: 2800,
    weightG: 1520,
    tier: 5,
    ratings: { performance: 10, comfort: 7.5, durability: 8, climbing: 8.5, descending: 9.5 },
    maintenance: "low",
    compat: { wheelSize: "700c", freehubOptions: ["HG", "XDR"] },
    specs: [
      { label: "Rim depth", value: "51 / 60 mm" },
      { label: "Hubs", value: "DT Swiss 180 internals" },
      { label: "Weight", value: "≈1,520 g (set)" },
    ],
    summary: "Deep aero wheels that stay stable in crosswinds.",
    pros: ["Very aero", "Stable in wind"],
    cons: ["Expensive"],
    visual: { rimDepthMm: 55, color: "#0d0d0d" },
  },
  {
    id: "zipp-303-firecrest",
    category: "wheels",
    disciplines: ["road"],
    brand: "Zipp",
    model: "303 Firecrest Tubeless",
    priceEur: 1500,
    weightG: 1530,
    tier: 4,
    ratings: { performance: 9, comfort: 8.5, durability: 8.5, climbing: 8.5, descending: 8.5 },
    maintenance: "low",
    compat: { wheelSize: "700c", freehubOptions: ["HG", "XDR"] },
    specs: [
      { label: "Rim depth", value: "40 mm" },
      { label: "Internal width", value: "25 mm, hookless" },
      { label: "Weight", value: "≈1,530 g (set)" },
    ],
    summary: "Versatile all-rounder with wide, comfortable rims.",
    pros: ["Comfortable with wide tires", "Good value carbon"],
    cons: ["Hookless — check tire compatibility"],
    visual: { rimDepthMm: 40, color: "#0d0d0d" },
  },
  {
    id: "shimano-da-c50",
    category: "wheels",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace WH-R9270-C50",
    priceEur: 2099,
    weightG: 1460,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 9, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { wheelSize: "700c", freehubOptions: ["HG"] },
    specs: [
      { label: "Rim depth", value: "50 mm" },
      { label: "Freehub", value: "Shimano HG only" },
      { label: "Weight", value: "≈1,460 g (set)" },
    ],
    summary: "Light, reliable aero wheels from Shimano.",
    pros: ["Light for 50 mm", "Durable hubs"],
    cons: ["Only available with a Shimano freehub"],
    visual: { rimDepthMm: 50, color: "#0d0d0d" },
  },
  {
    id: "dt-pr-1600",
    category: "wheels",
    disciplines: ["road"],
    brand: "DT Swiss",
    model: "PR 1600 Spline 23",
    priceEur: 599,
    weightG: 1650,
    tier: 3,
    ratings: { performance: 7.5, comfort: 8, durability: 9.5, climbing: 7.5, descending: 7.5 },
    maintenance: "low",
    compat: { wheelSize: "700c", freehubOptions: ["HG", "XDR"] },
    specs: [
      { label: "Rim", value: "Aluminium, 23 mm deep" },
      { label: "Weight", value: "≈1,650 g (set)" },
    ],
    summary: "A durable aluminium training wheelset.",
    pros: ["Affordable", "Very durable"],
    cons: ["Not aero"],
    visual: { rimDepthMm: 23, color: "#1a1a1a" },
  },

  // ─── Tires (pair) ────────────────────────────────────────────────────────
  {
    id: "conti-gp5000-str-28",
    category: "tires",
    disciplines: ["road"],
    brand: "Continental",
    model: "Grand Prix 5000 S TR 28 mm (pair)",
    priceEur: 150,
    weightG: 580,
    tier: 5,
    ratings: { performance: 9.5, comfort: 8, durability: 8, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { wheelSize: "700c", tireWidthMm: 28 },
    specs: [
      { label: "Width", value: "28 mm" },
      { label: "Type", value: "Tubeless ready" },
    ],
    summary: "The benchmark road tire for speed and grip.",
    pros: ["Low rolling resistance", "Great grip"],
    cons: ["Can be tight to mount"],
  },
  {
    id: "pirelli-pzero-race-tlr-30",
    category: "tires",
    disciplines: ["road"],
    brand: "Pirelli",
    model: "P Zero Race TLR 30 mm (pair)",
    priceEur: 140,
    weightG: 620,
    tier: 4,
    ratings: { performance: 9, comfort: 9, durability: 8, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { wheelSize: "700c", tireWidthMm: 30 },
    specs: [
      { label: "Width", value: "30 mm" },
      { label: "Type", value: "Tubeless" },
    ],
    summary: "A comfortable, grippy tubeless race tire.",
    pros: ["Comfortable", "Grippy in the wet"],
    cons: ["Slightly heavier than 28 mm"],
  },
  {
    id: "vittoria-corsa-pro-32",
    category: "tires",
    disciplines: ["road"],
    brand: "Vittoria",
    model: "Corsa Pro TLR 32 mm (pair)",
    priceEur: 160,
    weightG: 680,
    tier: 5,
    ratings: { performance: 9, comfort: 9.5, durability: 7.5, climbing: 8, descending: 9 },
    maintenance: "low",
    compat: { wheelSize: "700c", tireWidthMm: 32 },
    specs: [
      { label: "Width", value: "32 mm" },
      { label: "Type", value: "Tubeless ready, cotton-feel casing" },
    ],
    summary: "A supple, wide tire for comfort on rough roads.",
    pros: ["Very supple", "Excellent comfort"],
    cons: ["Needs 32 mm clearance"],
  },

  // ─── Groupsets (shifters + derailleurs) ──────────────────────────────────
  {
    id: "shimano-da-r9200",
    category: "groupset",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace Di2 R9200 (shifters + derailleurs)",
    priceEur: 1649,
    weightG: 720,
    tier: 5,
    ratings: { performance: 10, comfort: 8, durability: 9, climbing: 9.5, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12", speeds: 12, electronic: true, brakeSystem: "shimano" },
    specs: [
      { label: "Speeds", value: "2×12" },
      { label: "Shifting", value: "Semi-wireless Di2" },
      { label: "Brake levers", value: "Hydraulic, integrated" },
    ],
    summary: "Shimano's flagship electronic road groupset.",
    pros: ["Fastest Shimano shifting", "Long battery life"],
    cons: ["Expensive"],
  },
  {
    id: "shimano-ultegra-r8100",
    category: "groupset",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Ultegra Di2 R8100 (shifters + derailleurs)",
    priceEur: 999,
    weightG: 800,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 9, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12", speeds: 12, electronic: true, brakeSystem: "shimano" },
    specs: [
      { label: "Speeds", value: "2×12" },
      { label: "Shifting", value: "Semi-wireless Di2" },
    ],
    summary: "Dura-Ace function with a small weight penalty.",
    pros: ["Same shift speed as Dura-Ace", "Great value"],
    cons: ["~80 g heavier"],
  },
  {
    id: "sram-red-axs-e1",
    category: "groupset",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Red AXS E1 (shifters + derailleurs)",
    priceEur: 1899,
    weightG: 650,
    tier: 5,
    ratings: { performance: 10, comfort: 8.5, durability: 8.5, climbing: 9.5, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs", speeds: 12, electronic: true, brakeSystem: "sram" },
    specs: [
      { label: "Speeds", value: "2×12" },
      { label: "Shifting", value: "Wireless AXS" },
    ],
    summary: "SRAM's lightest, most ergonomic road groupset.",
    pros: ["Fully wireless", "Excellent lever ergonomics"],
    cons: ["Most expensive option"],
  },
  {
    id: "sram-force-axs",
    category: "groupset",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Force AXS (shifters + derailleurs)",
    priceEur: 1149,
    weightG: 780,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 8.5, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs", speeds: 12, electronic: true, brakeSystem: "sram" },
    specs: [
      { label: "Speeds", value: "2×12" },
      { label: "Shifting", value: "Wireless AXS" },
    ],
    summary: "Wireless shifting at a lower price point.",
    pros: ["Fully wireless"],
    cons: ["Heavier than Red"],
  },

  // ─── Cranksets ───────────────────────────────────────────────────────────
  {
    id: "shimano-da-crank",
    category: "crankset",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace FC-R9200, 52/36",
    priceEur: 649,
    weightG: 690,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 9, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12" },
    specs: [{ label: "Chainrings", value: "52/36T" }],
    summary: "Stiff, light flagship crankset.",
    pros: ["Very stiff"],
    cons: ["Expensive"],
  },
  {
    id: "shimano-ultegra-crank",
    category: "crankset",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Ultegra FC-R8100, 52/36",
    priceEur: 329,
    weightG: 740,
    tier: 4,
    ratings: { performance: 9, comfort: 7.5, durability: 9, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12" },
    specs: [{ label: "Chainrings", value: "52/36T" }],
    summary: "Excellent value 12-speed road crank.",
    pros: ["Great value"],
    cons: [],
  },
  {
    id: "sram-red-e1-crank",
    category: "crankset",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Red AXS E1 Crankset, 48/35",
    priceEur: 749,
    weightG: 610,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 8.5, climbing: 9.5, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs" },
    specs: [{ label: "Chainrings", value: "48/35T" }],
    summary: "Ultralight carbon road crank.",
    pros: ["Very light"],
    cons: ["Expensive"],
  },
  {
    id: "sram-force-crank",
    category: "crankset",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Force AXS Crankset, 48/35",
    priceEur: 399,
    weightG: 780,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7.5, durability: 8.5, climbing: 8.5, descending: 8.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs" },
    specs: [{ label: "Chainrings", value: "48/35T" }],
    summary: "Carbon road crank with SRAM's wide-range gearing.",
    pros: ["Good value"],
    cons: ["Heavier than Red"],
  },

  // ─── Cassettes ───────────────────────────────────────────────────────────
  {
    id: "shimano-da-cassette",
    category: "cassette",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace CS-R9200, 11–30T",
    priceEur: 299,
    weightG: 223,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 8, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12", speeds: 12, freehub: "HG" },
    specs: [
      { label: "Range", value: "11–30T" },
      { label: "Freehub", value: "Shimano HG (road 12s)" },
    ],
    summary: "Light titanium road cassette.",
    pros: ["Very light"],
    cons: ["Expensive wear part"],
  },
  {
    id: "shimano-ultegra-cassette",
    category: "cassette",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Ultegra CS-R8100, 11–30T",
    priceEur: 109,
    weightG: 290,
    tier: 4,
    ratings: { performance: 9, comfort: 7.5, durability: 9, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12", speeds: 12, freehub: "HG" },
    specs: [
      { label: "Range", value: "11–30T" },
      { label: "Freehub", value: "Shimano HG (road 12s)" },
    ],
    summary: "Durable, affordable road cassette.",
    pros: ["Great value"],
    cons: [],
  },
  {
    id: "sram-red-xg1290",
    category: "cassette",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Red XG-1290, 10–28T",
    priceEur: 379,
    weightG: 180,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 7.5, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs", speeds: 12, freehub: "XDR" },
    specs: [
      { label: "Range", value: "10–28T" },
      { label: "Freehub", value: "XDR" },
    ],
    summary: "SRAM's lightest road cassette.",
    pros: ["Very light"],
    cons: ["Expensive"],
  },
  {
    id: "sram-force-xg1270",
    category: "cassette",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Force XG-1270, 10–33T",
    priceEur: 199,
    weightG: 285,
    tier: 4,
    ratings: { performance: 8.5, comfort: 8, durability: 8.5, climbing: 9, descending: 8.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs", speeds: 12, freehub: "XDR" },
    specs: [
      { label: "Range", value: "10–33T" },
      { label: "Freehub", value: "XDR" },
    ],
    summary: "Wide-range road cassette for hilly riding.",
    pros: ["Easier climbing gear"],
    cons: ["Bigger jumps between gears"],
  },

  // ─── Chains ──────────────────────────────────────────────────────────────
  {
    id: "shimano-da-chain",
    category: "chain",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace CN-M9100 12s",
    priceEur: 69,
    weightG: 245,
    tier: 5,
    ratings: { performance: 9, comfort: 7.5, durability: 8.5, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "shimano-road-12", speeds: 12, chain: "shimano-hg" },
    specs: [{ label: "Speeds", value: "12" }],
    summary: "Shimano's 12-speed chain used on Dura-Ace.",
    pros: ["Smooth, durable"],
    cons: [],
  },
  {
    id: "sram-red-flattop",
    category: "chain",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Red Flattop Chain",
    priceEur: 85,
    weightG: 230,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7.5, durability: 8, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs", speeds: 12, chain: "flattop" },
    specs: [{ label: "Standard", value: "Flattop" }],
    summary: "Required chain type for SRAM AXS road.",
    pros: ["Light, quiet"],
    cons: ["Only for SRAM AXS road"],
  },
  {
    id: "sram-force-flattop",
    category: "chain",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Force Flattop Chain",
    priceEur: 49,
    weightG: 250,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7.5, durability: 8.5, climbing: 8.5, descending: 8.5 },
    maintenance: "low",
    compat: { drivetrain: "sram-road-axs", speeds: 12, chain: "flattop" },
    specs: [{ label: "Standard", value: "Flattop" }],
    summary: "Affordable Flattop chain.",
    pros: ["Good value"],
    cons: [],
  },

  // ─── Brakes (calipers + rotors; levers are part of the groupset) ─────────
  {
    id: "shimano-da-br-r9270",
    category: "brakes",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace BR-R9270 calipers + RT-CL900 rotors",
    priceEur: 399,
    weightG: 380,
    tier: 5,
    ratings: { performance: 9.5, comfort: 8, durability: 9, climbing: 9, descending: 9.5 },
    maintenance: "low",
    compat: { brakeSystem: "shimano", brakeMounts: ["flat-mount"], rotorsMm: [160, 140] },
    specs: [
      { label: "Mount", value: "Flat mount" },
      { label: "Rotors", value: "160 / 140 mm" },
      { label: "Fluid", value: "Mineral oil" },
    ],
    summary: "Light, powerful road disc brakes.",
    pros: ["Excellent modulation"],
    cons: ["Only works with Shimano hydraulic levers"],
  },
  {
    id: "shimano-ultegra-br-r8170",
    category: "brakes",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Ultegra BR-R8170 calipers + RT-MT800 rotors",
    priceEur: 219,
    weightG: 420,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 9, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { brakeSystem: "shimano", brakeMounts: ["flat-mount"], rotorsMm: [160, 160] },
    specs: [
      { label: "Mount", value: "Flat mount" },
      { label: "Rotors", value: "160 / 160 mm" },
    ],
    summary: "Dura-Ace performance at a lower price.",
    pros: ["Great value"],
    cons: ["Only works with Shimano hydraulic levers"],
  },
  {
    id: "sram-red-e1-brakes",
    category: "brakes",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Red AXS E1 calipers + Paceline X rotors",
    priceEur: 429,
    weightG: 360,
    tier: 5,
    ratings: { performance: 9.5, comfort: 8, durability: 8.5, climbing: 9, descending: 9.5 },
    maintenance: "medium",
    compat: { brakeSystem: "sram", brakeMounts: ["flat-mount"], rotorsMm: [160, 160] },
    specs: [
      { label: "Mount", value: "Flat mount" },
      { label: "Rotors", value: "160 / 160 mm" },
      { label: "Fluid", value: "DOT 5.1" },
    ],
    summary: "Light SRAM road brakes.",
    pros: ["Very light", "Good power"],
    cons: ["Only works with SRAM hydraulic levers"],
  },
  {
    id: "sram-force-brakes",
    category: "brakes",
    disciplines: ["road"],
    brand: "SRAM",
    model: "Force AXS calipers + Centerline XR rotors",
    priceEur: 269,
    weightG: 420,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 8.5, climbing: 8.5, descending: 9 },
    maintenance: "medium",
    compat: { brakeSystem: "sram", brakeMounts: ["flat-mount"], rotorsMm: [160, 160] },
    specs: [
      { label: "Mount", value: "Flat mount" },
      { label: "Rotors", value: "160 / 160 mm" },
    ],
    summary: "SRAM road brakes at a lower price.",
    pros: ["Good value"],
    cons: ["Only works with SRAM hydraulic levers"],
  },

  // ─── Handlebars / stems ──────────────────────────────────────────────────
  {
    id: "zipp-sl70-ergo",
    category: "handlebar",
    disciplines: ["road"],
    brand: "Zipp",
    model: "Service Course SL-70 Ergo, 42 cm",
    priceEur: 129,
    weightG: 255,
    tier: 3,
    ratings: { performance: 8, comfort: 8, durability: 9, climbing: 8, descending: 8 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Material", value: "Aluminium" },
      { label: "Clamp", value: "31.8 mm" },
    ],
    summary: "Classic ergonomic alloy road bar.",
    pros: ["Durable", "Comfortable drops"],
    cons: ["Heavier than carbon"],
  },
  {
    id: "enve-ses-aero-bar",
    category: "handlebar",
    disciplines: ["road"],
    brand: "ENVE",
    model: "SES AR Road Bar, 40 cm",
    priceEur: 399,
    weightG: 235,
    tier: 5,
    ratings: { performance: 9.5, comfort: 8, durability: 8.5, climbing: 8.5, descending: 9 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Material", value: "Carbon, aero tops" },
      { label: "Clamp", value: "31.8 mm" },
    ],
    summary: "An aero carbon bar with flared drops.",
    pros: ["Aero", "Stable in the drops"],
    cons: ["Expensive"],
  },
  {
    id: "roval-alpinist-bar",
    category: "handlebar",
    disciplines: ["road"],
    brand: "Roval",
    model: "Alpinist Carbon Handlebar, 42 cm",
    priceEur: 299,
    weightG: 195,
    tier: 5,
    ratings: { performance: 9, comfort: 8.5, durability: 8, climbing: 10, descending: 8 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Material", value: "Carbon" },
      { label: "Clamp", value: "31.8 mm" },
    ],
    summary: "An ultralight round carbon bar.",
    pros: ["Very light"],
    cons: ["Not aero"],
  },
  {
    id: "zipp-sc-sl-stem",
    category: "stem",
    disciplines: ["road"],
    brand: "Zipp",
    model: "Service Course SL, 110 mm",
    priceEur: 95,
    weightG: 125,
    tier: 4,
    ratings: { performance: 8.5, comfort: 7.5, durability: 9, climbing: 8.5, descending: 8.5 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Clamp", value: "31.8 mm" },
      { label: "Length", value: "110 mm" },
    ],
    summary: "Light forged alloy road stem.",
    pros: ["Light", "Affordable"],
    cons: [],
  },
  {
    id: "enve-road-stem",
    category: "stem",
    disciplines: ["road"],
    brand: "ENVE",
    model: "Road Stem, 110 mm",
    priceEur: 279,
    weightG: 120,
    tier: 5,
    ratings: { performance: 9, comfort: 7.5, durability: 8.5, climbing: 9, descending: 8.5 },
    maintenance: "low",
    compat: { barClampMm: 31.8 },
    specs: [
      { label: "Clamp", value: "31.8 mm" },
      { label: "Length", value: "110 mm" },
    ],
    summary: "Carbon-wrapped road stem.",
    pros: ["Light"],
    cons: ["Expensive for the gain"],
  },

  // ─── Seatposts ───────────────────────────────────────────────────────────
  {
    id: "tarmac-sl8-seatpost",
    category: "seatpost",
    disciplines: ["road"],
    brand: "Specialized",
    model: "S-Works Tarmac SL8 Seatpost",
    priceEur: 349,
    weightG: 160,
    tier: 5,
    ratings: { performance: 9.5, comfort: 7, durability: 8, climbing: 9, descending: 9 },
    maintenance: "low",
    compat: { seatpostFits: ["tarmac-sl8"] },
    specs: [{ label: "Fit", value: "Tarmac SL8 only" }],
    summary: "Frame-specific aero seatpost.",
    pros: ["Aero"],
    cons: ["Only fits the Tarmac SL8"],
  },
  {
    id: "aeroad-seatpost",
    category: "seatpost",
    disciplines: ["road"],
    brand: "Canyon",
    model: "Aeroad SP0070 Seatpost",
    priceEur: 199,
    weightG: 200,
    tier: 4,
    ratings: { performance: 9, comfort: 6.5, durability: 8, climbing: 8, descending: 9 },
    maintenance: "low",
    compat: { seatpostFits: ["aeroad"] },
    specs: [{ label: "Fit", value: "Aeroad only" }],
    summary: "Frame-specific aero seatpost.",
    pros: ["Aero"],
    cons: ["Only fits the Aeroad"],
  },
  {
    id: "roval-alpinist-seatpost",
    category: "seatpost",
    disciplines: ["road"],
    brand: "Roval",
    model: "Alpinist Carbon Seatpost 27.2",
    priceEur: 299,
    weightG: 180,
    tier: 5,
    ratings: { performance: 9, comfort: 8.5, durability: 8, climbing: 9.5, descending: 8 },
    maintenance: "low",
    compat: { seatpostFits: ["27.2"] },
    specs: [{ label: "Diameter", value: "27.2 mm" }],
    summary: "Light round carbon seatpost.",
    pros: ["Light", "Compliant"],
    cons: [],
  },

  // ─── Saddles / pedals ────────────────────────────────────────────────────
  {
    id: "sworks-power-mirror",
    category: "saddle",
    disciplines: ["road"],
    brand: "Specialized",
    model: "S-Works Power with Mirror",
    priceEur: 399,
    weightG: 188,
    tier: 5,
    ratings: { performance: 9, comfort: 9.5, durability: 8, climbing: 9, descending: 8.5 },
    maintenance: "low",
    compat: {},
    specs: [
      { label: "Padding", value: "3D-printed Mirror" },
      { label: "Rails", value: "Carbon" },
    ],
    summary: "3D-printed padding for pressure relief.",
    pros: ["Excellent comfort"],
    cons: ["Expensive"],
  },
  {
    id: "fizik-antares-r3",
    category: "saddle",
    disciplines: ["road"],
    brand: "Fizik",
    model: "Vento Antares R3",
    priceEur: 139,
    weightG: 210,
    tier: 3,
    ratings: { performance: 8.5, comfort: 7.5, durability: 8.5, climbing: 8.5, descending: 8 },
    maintenance: "low",
    compat: {},
    specs: [{ label: "Rails", value: "Kium" }],
    summary: "A flat, supportive race saddle.",
    pros: ["Good value"],
    cons: ["Firm"],
  },
  {
    id: "shimano-da-pd-r9200",
    category: "pedals",
    disciplines: ["road"],
    brand: "Shimano",
    model: "Dura-Ace PD-R9200 SPD-SL",
    priceEur: 229,
    weightG: 228,
    tier: 5,
    ratings: { performance: 9.5, comfort: 8, durability: 9, climbing: 9.5, descending: 9 },
    maintenance: "low",
    compat: { pedalType: "clipless-road" },
    specs: [{ label: "Weight", value: "≈228 g (pair)" }],
    summary: "Light, stiff road pedals.",
    pros: ["Wide platform", "Durable"],
    cons: [],
  },
  {
    id: "look-keo-blade-carbon",
    category: "pedals",
    disciplines: ["road"],
    brand: "Look",
    model: "Kéo Blade Carbon",
    priceEur: 149,
    weightG: 250,
    tier: 4,
    ratings: { performance: 9, comfort: 8, durability: 8.5, climbing: 9, descending: 8.5 },
    maintenance: "low",
    compat: { pedalType: "clipless-road" },
    specs: [{ label: "Body", value: "Carbon" }],
    summary: "Carbon-blade retention road pedal.",
    pros: ["Light", "Good value"],
    cons: [],
  },
];
